export const testProductArray = [
  {
    id: 1,
    inStock: true,
    stockColor: "green",
    stockIndicator: "In Stock",
    photo: "/assets/images/TestProductPhoto.png",
    photo2: "/assets/images/TestProductPhoto2.png",
    photo3: "/assets/images/TestProductPhoto3.png",
    photo4: "/assets/images/TestProductPhoto4.png",
    photo5: "/assets/images/TestProductPhoto5.png",
    colorfulStarCount: 4,
    reviewCount: "4 reviews",
    description: "MSI GeForce RTX 3070",
    // specialPrice: "600$",
    discountedPrice: "560$",
  },
  {
    id: 2,
    inStock: true,
    stockColor: "green",
    stockIndicator: "In Stock",
    photo: "assets/images/TestProductPhoto.png",
    photo2: "assets/images/TestProductPhoto2.png",
    photo3: "assets/images/TestProductPhoto3.png",
    photo4: "assets/images/TestProductPhoto4.png",
    photo5: "assets/images/TestProductPhoto5.png",
    colorfulStarCount: 5,
    reviewCount: "12 reviews",
    description: "Nvidia GeForce RTX 3080 Ti",
    specialPrice: "300$",
    discountedPrice: "280$",
  },
  {
    id: 3,
    inStock: false,
    stockColor: "red",
    stockIndicator: "Not In Stock",
    photo: "assets/images/TestProductPhoto.png",
    photo2: "assets/images/TestProductPhoto2.png",
    photo3: "assets/images/TestProductPhoto3.png",
    photo4: "assets/images/TestProductPhoto4.png",
    photo5: "assets/images/TestProductPhoto5.png",
    colorfulStarCount: 2,
    reviewCount: "1 reviews",
    description: "AMD Radeon RX 6800",
    specialPrice: "620$",
    discountedPrice: "580$",
  },
  {
    id: 4,
    inStock: false,
    stockColor: "red",
    stockIndicator: "Not In Stock",
    photo: "assets/images/TestProductPhoto.png",
    photo2: "assets/images/TestProductPhoto2.png",
    photo3: "assets/images/TestProductPhoto3.png",
    photo4: "assets/images/TestProductPhoto4.png",
    photo5: "assets/images/TestProductPhoto5.png",
    colorfulStarCount: 3,
    reviewCount: "8 reviews",
    description: "MSI RTX 3090 Gaming X Trio",
    specialPrice: "460$",
    discountedPrice: "380$",
  },
  {
    id: 5,
    inStock: false,
    stockColor: "red",
    stockIndicator: "Not In Stock",
    photo: "assets/images/TestProductPhoto.png",
    photo2: "assets/images/TestProductPhoto2.png",
    photo3: "assets/images/TestProductPhoto3.png",
    photo4: "assets/images/TestProductPhoto4.png",
    photo5: "assets/images/TestProductPhoto5.png",
    colorfulStarCount: 5,
    reviewCount: "90 reviews",
    description: "Nvidia GeForce GTX 1660 Ti",
    // specialPrice: "750$",
    discountedPrice: "590$",
  },
  {
    id: 6,
    inStock: true,
    stockColor: "green",
    stockIndicator: "In Stock",
    photo: "assets/images/TestProductPhoto.png",
    photo2: "assets/images/TestProductPhoto2.png",
    photo3: "assets/images/TestProductPhoto3.png",
    photo4: "assets/images/TestProductPhoto4.png",
    photo5: "assets/images/TestProductPhoto5.png",
    colorfulStarCount: 1,
    reviewCount: "71 reviews",
    description: "Nvidia Quadro RTX 5000",
    specialPrice: "200$",
    discountedPrice: "60$",
  },
  {
    id: 7,
    inStock: false,
    stockColor: "red",
    stockIndicator: "Not In Stock",
    photo: "assets/images/TestProductPhoto.png",
    photo2: "assets/images/TestProductPhoto2.png",
    photo3: "assets/images/TestProductPhoto3.png",
    photo4: "assets/images/TestProductPhoto4.png",
    photo5: "assets/images/TestProductPhoto5.png",
    colorfulStarCount: 3,
    reviewCount: "52 reviews",
    description: "Gigabyte Aorus GeForce RTX 3080",
    specialPrice: "630$",
    discountedPrice: "500$",
  },
  {
    id: 8,
    inStock: true,
    stockColor: "green",
    stockIndicator: "In Stock",
    photo: "assets/images/TestProductPhoto.png",
    photo2: "assets/images/TestProductPhoto2.png",
    photo3: "assets/images/TestProductPhoto3.png",
    photo4: "assets/images/TestProductPhoto4.png",
    photo5: "assets/images/TestProductPhoto5.png",
    colorfulStarCount: 5,
    reviewCount: "13 reviews",
    description: "Nvidia Quadro RTX 4000",
    specialPrice: "530$",
    discountedPrice: "500$",
  },
  {
    id: 9,
    inStock: false,
    stockColor: "red",
    stockIndicator: "Not In Stock",
    photo: "assets/images/TestProductPhoto.png",
    photo2: "assets/images/TestProductPhoto2.png",
    photo3: "assets/images/TestProductPhoto3.png",
    photo4: "assets/images/TestProductPhoto4.png",
    photo5: "assets/images/TestProductPhoto5.png",
    colorfulStarCount: 2,
    reviewCount: "67 reviews",
    description: "Nintendo Switch Pro",
    // specialPrice: "490$",
    discountedPrice: "360$",
  },
  {
    id: 10,
    inStock: true,
    stockColor: "green",
    stockIndicator: "In Stock",
    photo: "assets/images/TestProductPhoto.png",
    photo2: "assets/images/TestProductPhoto2.png",
    photo3: "assets/images/TestProductPhoto3.png",
    photo4: "assets/images/TestProductPhoto4.png",
    photo5: "assets/images/TestProductPhoto5.png",
    colorfulStarCount: 4,
    reviewCount: "96 reviews",
    description: "Sony PlayStation 4 Pro",
    specialPrice: "600$",
    discountedPrice: "520$",
  },
  {
    id: 11,
    inStock: true,
    stockColor: "green",
    stockIndicator: "In Stock",
    photo: "assets/images/TestProductPhoto.png",
    photo2: "assets/images/TestProductPhoto2.png",
    photo3: "assets/images/TestProductPhoto3.png",
    photo4: "assets/images/TestProductPhoto4.png",
    photo5: "assets/images/TestProductPhoto5.png",
    colorfulStarCount: 5,
    reviewCount: "42 reviews",
    description: "Sony PlayStation 5",
    specialPrice: "670$",
    discountedPrice: "590$",
  },
  {
    id: 12,
    inStock: false,
    stockColor: "red",
    stockIndicator: "Not In Stock",
    photo: "assets/images/TestProductPhoto.png",
    photo2: "assets/images/TestProductPhoto2.png",
    photo3: "assets/images/TestProductPhoto3.png",
    photo4: "assets/images/TestProductPhoto4.png",
    photo5: "assets/images/TestProductPhoto5.png",
    colorfulStarCount: 5,
    reviewCount: "29 reviews",
    description: "Mademax RS-1 Handheld Game Console",
    // specialPrice: "590$",
    discountedPrice: "500$",
  },
];
