export const ArrayForLinks = [
  {
    id: 1,
    title: "Information",
    value: [
      "About Us",
      "Privacy Policy",
      "Search",
      "Terms",
      "Orders and Returns",
      "Contact Us",
      "Advanced Search",
    ],
  },
  {
    id: 2,
    title: "Vapes",
    value: [
      "CPUS",
      "Hard Drives (Internal)",
      "Graphic Cards",
      "Keyboards / Mouse",
      "Cases / Cooling",
      "RAM (Memory)",
      "Software",
      "Motherboards",
    ],
  },
  {
    id: 3,
    title: "Liquids",
    value: [
      "Custom PCs",
      "Servers",
      "MSI All-In-One PCs",
      "HP / Compaq PCs",
      "ASUS PCs",
      "Tecs PCs",
    ],
  },
  {
    id: 4,
    title: "Pods",
    value: [
      "Evryday Use Notebooks",
      "MSI Workstation Series",
      "MSI Prestige Series",
      "Tablets and Pads",
      "Netbooks",
      "Infinity Gaming Notebooks",
    ],
  },
  {
    id: 5,
    title: "Coils",
    value: [
      "Address: 1234 Street Adress",
      "Phones: (+995) 551 37 07 37",
      "Open Hours :",
      "Monday: 9:00 AM - 5:30 PM",
      "Thursday: 9:00 AM - 5:30 PM",
      "Friday: 9:00 AM - 6:00 PM",
      "Saturday: 11:00 AM - 5:00 PM",
      "E-mail: shop@email.com",
    ],
  },
];
